In [1]:
import numpy as np

In [2]:
# Implementation of Binomial Tree Options Pricing (American Options)
def Option_Val(n, S, K, r, v, T, PC, q=0):
    dt = T/n                    
    u = np.exp(v*np.sqrt(dt)) 
    d = 1.0/u                     
    p = (np.exp((r-q)*dt)-d)/(u-d)   
    Pm = np.zeros((n+1, n+1)) # Underlying Asset Price  
    Cm = np.zeros((n+1, n+1)) # Option Value
    tmp = np.zeros((2,n+1))
    for j in range(n+1):
        tmp[0,j] = S*np.power(d,j)
        tmp[1,j] = S*np.power(u,j)
    
    tot = np.unique(tmp)
    c=n
    for i in range(c+1):
        for j in range(c+1):
            Pm[i,j-c-1] = tot[(n-i)+j]
        c=c-1
    for j in range(n+1, 0, -1):
        for i in range(j):
            if (PC == 1):                               
                if(j == n+1):
                    Cm[i,j-1] = max(K-Pm[i,j-1], 0)     
                else:
                    early = max(K-Pm[i,j-1], 0) # early excercise value
                    wait = np.exp(-r*dt) * (p*Cm[i,j] + (1-p)*Cm[i+1,j]) # wait until the end value
                    if early < wait:
                        Cm[i,j-1] = wait
                    else:
                        Cm[i,j-1] = early
            elif (PC == 0):                               
                if (j == n + 1):
                    Cm[i,j-1] = max(Pm[i,j-1]-K, 0)     
                else:
                    early = max(Pm[i,j-1]-K, 0)  # early excercise value
                    wait = np.exp(-r*dt) * (p*Cm[i,j] + (1-p)*Cm[i+1,j]) # wait until the end value
                    if early < wait:
                        Cm[i,j-1] = wait
                    else:
                        Cm[i,j-1] = early       
    return Pm, Cm

In [3]:
# Hull Example 18.1
S = 50
k = 50
r = .1
v = .4
T = 0.4167
n = 5
PC = 1 # 0 for call, 1 for put
Pm,Cm = Option_Val(n,S,k,r,v,T,PC)
print('Stock Prices:\n',np.matrix(Pm.astype(float)))
print('Option Values:\n',np.matrix(Cm.astype(float)))
print('Option Value at t = 0:',Cm[0][0])

Stock Prices:
 [[ 50.          56.12030433  62.98977115  70.70010253  79.35422539
   89.06766557]
 [  0.          44.54715686  50.          56.12030433  62.98977115
   70.70010253]
 [  0.           0.          39.68898369  44.54715686  50.          56.12030433]
 [  0.           0.           0.          35.36062765  39.68898369
   44.54715686]
 [  0.           0.           0.           0.          31.50430853
   35.36062765]
 [  0.           0.           0.           0.           0.          28.06854748]]
Option Values:
 [[  4.48859919   2.1625898    0.63600521   0.           0.           0.        ]
 [  0.           6.95996679   3.77126872   1.30171162   0.           0.        ]
 [  0.           0.          10.36163584   6.3782645    2.66421269   0.        ]
 [  0.           0.           0.          14.63937235  10.31101631
    5.45284314]
 [  0.           0.           0.           0.          18.49569147
   14.63937235]
 [  0.           0.           0.           0.           0.       

In [4]:
# Hull Excercise 18.10
S = 50
k = 49
r = .05
v = .3
T = 0.75
n = 3
PC = 1 # 0 for call, 1 for put
Pm,Cm = Option_Val(n,S,k,r,v,T,PC)
print('Stock Prices:\n',np.matrix(Pm.astype(float)))
print('Option Values:\n',np.matrix(Cm.astype(float)))
print('Option Value at t = 0:',Cm[0][0])

Stock Prices:
 [[ 50.          58.09171214  67.49294038  78.41560927]
 [  0.          43.03539882  50.          58.09171214]
 [  0.           0.          37.04091103  43.03539882]
 [  0.           0.           0.          31.88140758]]
Option Values:
 [[  4.28922495   1.42918731   0.           0.        ]
 [  0.           7.30821389   2.91968017   0.        ]
 [  0.           0.          11.95908897   5.96460118]
 [  0.           0.           0.          17.11859242]]
Option Value at t = 0: 4.28922495473


In [5]:
# Hull Excercise 18.10
S = 50
k = 49
r = .05
v = .3
T = 0.75
n = 500 
PC = 1 # 0 for call, 1 for put
Pm,Cm = Option_Val(n,S,k,r,v,T,PC)
print('Option Value at t = 0:',Cm[0][0])

Option Value at t = 0: 3.90149932065


In [6]:
# Hull Excercise 18.11
F = 400
k = 420
r = .06
q = r
v = .35
T = 0.75
n = 3
PC = 0 # 0 for call, 1 for put
Pm,Cm = Option_Val(n,F,k,r,v,T,PC,q)
print('Futures Prices:\n',np.matrix(Pm.astype(float)))
print('Option Values:\n',np.matrix(Cm.astype(float)))
print('Option Value at t = 0:',Cm[0][0])
print('Delta Approximation is:' ,(Cm[0][1]-Cm[1][1])/(Pm[0][1]-Pm[1][1]))

Futures Prices:
 [[ 400.          476.49848664  567.62701944  676.18353935]
 [   0.          335.78280831  400.          476.49848664]
 [   0.            0.          281.87523589  335.78280831]
 [   0.            0.            0.          236.62214575]]
Option Values:
 [[  42.06767275   79.97099678  147.62701944  256.18353935]
 [   0.           11.41893556   25.3998539    56.49848664]
 [   0.            0.            0.            0.        ]
 [   0.            0.            0.            0.        ]]
Option Value at t = 0: 42.0676727535
Delta Approximation is: 0.487167187264


In [7]:
Pm,Cm = Option_Val(500,F,k,r,v,T,PC,q)
print('When n =500, Option Value at t = 0:',Cm[0][0])
print('When n= 500, Delta Approximation is:' ,(Cm[0][1]-Cm[1][1])/(Pm[0][1]-Pm[1][1]))

When n =500, Option Value at t = 0: 38.6082511847
When n= 500, Delta Approximation is: 0.480679370635


In [8]:
# Hull Excercise 18.14
S = 484
k = 480
r = .1
q = .03
v = .25
T = 2/12
n = 4
PC = 1 # 0 for call, 1 for put
Pm,Cm = Option_Val(n,S,k,r,v,T,PC,q)
print('Futures Prices:\n',np.matrix(Pm.astype(float)))
print('Option Values:\n',np.matrix(Cm.astype(float)))
print('Option Value at t = 0:',Cm[0][0])

Futures Prices:
 [[ 484.          509.34008814  536.00687063  564.0698073   593.60199456]
 [   0.          459.92060208  484.          509.34008814  536.00687063]
 [   0.            0.          437.039174    459.92060208  484.        ]
 [   0.            0.            0.          415.29611578  437.039174  ]
 [   0.            0.            0.            0.          394.63479259]]
Option Values:
 [[ 14.93323365   4.81481062   0.           0.           0.        ]
 [  0.          25.84302528   9.98643196   0.           0.        ]
 [  0.           0.          42.960826    20.7129275    0.        ]
 [  0.           0.           0.          64.70388422  42.960826  ]
 [  0.           0.           0.           0.          85.36520741]]
Option Value at t = 0: 14.9332336495
